version: '3.8'

services:
frontend:
build: ./frontend
networks:
- frontend_network
ports:
- "80:80"
deploy:
replicas: 3
restart_policy:
condition: on-failure

networks:
frontend_network:
driver: overlay
